apiVersion: v1
kind: Pod
metadata:
  name: app-1
  labels:
    foo: vitor
spec:
  containers:
  - name: app
    image: vitorenesduarte/tutorial
    env:
    - name: ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
---
apiVersion: v1
kind: Pod
metadata:
  name: app-2
  labels:
    foo: vitor
spec:
  containers:
  - name: app
    image: vitorenesduarte/tutorial
    env:
    - name: ID
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
